apiVersion: v2
name: msvc-chart
version: 1.0.0
description: Microservices project
type: application
sources:
  - https://github.com/Kislichenko/project1-2024
  - https://github.com/Kislichenko/project1-gateway-2024
  - https://github.com/Kislichenko/project1-deploy-2024
maintainers:
  - name: Bogdan K
    email: alex.volkov8319@gmail.ru
    url: 5.253.40.182
appVersion: 1.0.0